// Lista de países: nome (PT), código ISO2 (para bandeira SVG) e DDI
const COUNTRIES = [
  { n: "Brasil", c: "br", d: "55" },
  { n: "Portugal", c: "pt", d: "351" },
  { n: "Estados Unidos", c: "us", d: "1" },
  { n: "Afeganistão", c: "af", d: "93" },
  { n: "África do Sul", c: "za", d: "27" },
  { n: "Albânia", c: "al", d: "355" },
  { n: "Alemanha", c: "de", d: "49" },
  { n: "Andorra", c: "ad", d: "376" },
  { n: "Angola", c: "ao", d: "244" },
  { n: "Anguilla", c: "ai", d: "1264" },
  { n: "Antígua e Barbuda", c: "ag", d: "1268" },
  { n: "Arábia Saudita", c: "sa", d: "966" },
  { n: "Argélia", c: "dz", d: "213" },
  { n: "Argentina", c: "ar", d: "54" },
  { n: "Armênia", c: "am", d: "374" },
  { n: "Aruba", c: "aw", d: "297" },
  { n: "Austrália", c: "au", d: "61" },
  { n: "Áustria", c: "at", d: "43" },
  { n: "Azerbaijão", c: "az", d: "994" },
  { n: "Bahamas", c: "bs", d: "1242" },
  { n: "Bahrein", c: "bh", d: "973" },
  { n: "Bangladesh", c: "bd", d: "880" },
  { n: "Barbados", c: "bb", d: "1246" },
  { n: "Bélgica", c: "be", d: "32" },
  { n: "Belize", c: "bz", d: "501" },
  { n: "Benin", c: "bj", d: "229" },
  { n: "Bermudas", c: "bm", d: "1441" },
  { n: "Bielorrússia", c: "by", d: "375" },
  { n: "Bolívia", c: "bo", d: "591" },
  { n: "Bósnia e Herzegovina", c: "ba", d: "387" },
  { n: "Botswana", c: "bw", d: "267" },
  { n: "Brunei", c: "bn", d: "673" },
  { n: "Bulgária", c: "bg", d: "359" },
  { n: "Burkina Faso", c: "bf", d: "226" },
  { n: "Burundi", c: "bi", d: "257" },
  { n: "Butão", c: "bt", d: "975" },
  { n: "Cabo Verde", c: "cv", d: "238" },
  { n: "Camarões", c: "cm", d: "237" },
  { n: "Camboja", c: "kh", d: "855" },
  { n: "Canadá", c: "ca", d: "1" },
  { n: "Catar", c: "qa", d: "974" },
  { n: "Cazaquistão", c: "kz", d: "7" },
  { n: "Chade", c: "td", d: "235" },
  { n: "Chile", c: "cl", d: "56" },
  { n: "China", c: "cn", d: "86" },
  { n: "Chipre", c: "cy", d: "357" },
  { n: "Cingapura", c: "sg", d: "65" },
  { n: "Colômbia", c: "co", d: "57" },
  { n: "Comores", c: "km", d: "269" },
  { n: "Congo", c: "cg", d: "242" },
  { n: "Congo (RDC)", c: "cd", d: "243" },
  { n: "Coreia do Norte", c: "kp", d: "850" },
  { n: "Coreia do Sul", c: "kr", d: "82" },
  { n: "Costa do Marfim", c: "ci", d: "225" },
  { n: "Costa Rica", c: "cr", d: "506" },
  { n: "Croácia", c: "hr", d: "385" },
  { n: "Cuba", c: "cu", d: "53" },
  { n: "Dinamarca", c: "dk", d: "45" },
  { n: "Djibouti", c: "dj", d: "253" },
  { n: "Dominica", c: "dm", d: "1767" },
  { n: "Egito", c: "eg", d: "20" },
  { n: "El Salvador", c: "sv", d: "503" },
  { n: "Emirados Árabes Unidos", c: "ae", d: "971" },
  { n: "Equador", c: "ec", d: "593" },
  { n: "Eritreia", c: "er", d: "291" },
  { n: "Eslováquia", c: "sk", d: "421" },
  { n: "Eslovênia", c: "si", d: "386" },
  { n: "Espanha", c: "es", d: "34" },
  { n: "Estônia", c: "ee", d: "372" },
  { n: "Eswatini", c: "sz", d: "268" },
  { n: "Etiópia", c: "et", d: "251" },
  { n: "Fiji", c: "fj", d: "679" },
  { n: "Filipinas", c: "ph", d: "63" },
  { n: "Finlândia", c: "fi", d: "358" },
  { n: "França", c: "fr", d: "33" },
  { n: "Gabão", c: "ga", d: "241" },
  { n: "Gâmbia", c: "gm", d: "220" },
  { n: "Gana", c: "gh", d: "233" },
  { n: "Geórgia", c: "ge", d: "995" },
  { n: "Gibraltar", c: "gi", d: "350" },
  { n: "Granada", c: "gd", d: "1473" },
  { n: "Grécia", c: "gr", d: "30" },
  { n: "Groenlândia", c: "gl", d: "299" },
  { n: "Guadalupe", c: "gp", d: "590" },
  { n: "Guam", c: "gu", d: "1671" },
  { n: "Guatemala", c: "gt", d: "502" },
  { n: "Guiana", c: "gy", d: "592" },
  { n: "Guiana Francesa", c: "gf", d: "594" },
  { n: "Guiné", c: "gn", d: "224" },
  { n: "Guiné Equatorial", c: "gq", d: "240" },
  { n: "Guiné-Bissau", c: "gw", d: "245" },
  { n: "Haiti", c: "ht", d: "509" },
  { n: "Holanda (Países Baixos)", c: "nl", d: "31" },
  { n: "Honduras", c: "hn", d: "504" },
  { n: "Hong Kong", c: "hk", d: "852" },
  { n: "Hungria", c: "hu", d: "36" },
  { n: "Iêmen", c: "ye", d: "967" },
  { n: "Ilhas Cayman", c: "ky", d: "1345" },
  { n: "Ilhas Cook", c: "ck", d: "682" },
  { n: "Ilhas Faroé", c: "fo", d: "298" },
  { n: "Ilhas Marshall", c: "mh", d: "692" },
  { n: "Ilhas Salomão", c: "sb", d: "677" },
  { n: "Ilhas Virgens Britânicas", c: "vg", d: "1284" },
  { n: "Índia", c: "in", d: "91" },
  { n: "Indonésia", c: "id", d: "62" },
  { n: "Irã", c: "ir", d: "98" },
  { n: "Iraque", c: "iq", d: "964" },
  { n: "Irlanda", c: "ie", d: "353" },
  { n: "Islândia", c: "is", d: "354" },
  { n: "Israel", c: "il", d: "972" },
  { n: "Itália", c: "it", d: "39" },
  { n: "Jamaica", c: "jm", d: "1876" },
  { n: "Japão", c: "jp", d: "81" },
  { n: "Jordânia", c: "jo", d: "962" },
  { n: "Kuwait", c: "kw", d: "965" },
  { n: "Laos", c: "la", d: "856" },
  { n: "Lesoto", c: "ls", d: "266" },
  { n: "Letônia", c: "lv", d: "371" },
  { n: "Líbano", c: "lb", d: "961" },
  { n: "Libéria", c: "lr", d: "231" },
  { n: "Líbia", c: "ly", d: "218" },
  { n: "Liechtenstein", c: "li", d: "423" },
  { n: "Lituânia", c: "lt", d: "370" },
  { n: "Luxemburgo", c: "lu", d: "352" },
  { n: "Macau", c: "mo", d: "853" },
  { n: "Macedônia do Norte", c: "mk", d: "389" },
  { n: "Madagascar", c: "mg", d: "261" },
  { n: "Malásia", c: "my", d: "60" },
  { n: "Malawi", c: "mw", d: "265" },
  { n: "Maldivas", c: "mv", d: "960" },
  { n: "Mali", c: "ml", d: "223" },
  { n: "Malta", c: "mt", d: "356" },
  { n: "Marrocos", c: "ma", d: "212" },
  { n: "Martinica", c: "mq", d: "596" },
  { n: "Maurício", c: "mu", d: "230" },
  { n: "Mauritânia", c: "mr", d: "222" },
  { n: "México", c: "mx", d: "52" },
  { n: "Mianmar", c: "mm", d: "95" },
  { n: "Micronésia", c: "fm", d: "691" },
  { n: "Moçambique", c: "mz", d: "258" },
  { n: "Moldávia", c: "md", d: "373" },
  { n: "Mônaco", c: "mc", d: "377" },
  { n: "Mongólia", c: "mn", d: "976" },
  { n: "Montenegro", c: "me", d: "382" },
  { n: "Namíbia", c: "na", d: "264" },
  { n: "Nauru", c: "nr", d: "674" },
  { n: "Nepal", c: "np", d: "977" },
  { n: "Nicarágua", c: "ni", d: "505" },
  { n: "Níger", c: "ne", d: "227" },
  { n: "Nigéria", c: "ng", d: "234" },
  { n: "Noruega", c: "no", d: "47" },
  { n: "Nova Caledônia", c: "nc", d: "687" },
  { n: "Nova Zelândia", c: "nz", d: "64" },
  { n: "Omã", c: "om", d: "968" },
  { n: "País de Gales", c: "gb-wls", d: "44" },
  { n: "Panamá", c: "pa", d: "507" },
  { n: "Papua-Nova Guiné", c: "pg", d: "675" },
  { n: "Paquistão", c: "pk", d: "92" },
  { n: "Paraguai", c: "py", d: "595" },
  { n: "Peru", c: "pe", d: "51" },
  { n: "Polinésia Francesa", c: "pf", d: "689" },
  { n: "Polônia", c: "pl", d: "48" },
  { n: "Porto Rico", c: "pr", d: "1787" },
  { n: "Quênia", c: "ke", d: "254" },
  { n: "Quirguistão", c: "kg", d: "996" },
  { n: "Reino Unido", c: "gb", d: "44" },
  { n: "República Centro-Africana", c: "cf", d: "236" },
  { n: "República Dominicana", c: "do", d: "1809" },
  { n: "República Tcheca", c: "cz", d: "420" },
  { n: "Reunião", c: "re", d: "262" },
  { n: "Romênia", c: "ro", d: "40" },
  { n: "Ruanda", c: "rw", d: "250" },
  { n: "Rússia", c: "ru", d: "7" },
  { n: "Saara Ocidental", c: "eh", d: "212" },
  { n: "Samoa", c: "ws", d: "685" },
  { n: "San Marino", c: "sm", d: "378" },
  { n: "Santa Lúcia", c: "lc", d: "1758" },
  { n: "São Cristóvão e Névis", c: "kn", d: "1869" },
  { n: "São Tomé e Príncipe", c: "st", d: "239" },
  { n: "São Vicente e Granadinas", c: "vc", d: "1784" },
  { n: "Senegal", c: "sn", d: "221" },
  { n: "Serra Leoa", c: "sl", d: "232" },
  { n: "Sérvia", c: "rs", d: "381" },
  { n: "Seychelles", c: "sc", d: "248" },
  { n: "Síria", c: "sy", d: "963" },
  { n: "Somália", c: "so", d: "252" },
  { n: "Sri Lanka", c: "lk", d: "94" },
  { n: "Sudão", c: "sd", d: "249" },
  { n: "Sudão do Sul", c: "ss", d: "211" },
  { n: "Suécia", c: "se", d: "46" },
  { n: "Suíça", c: "ch", d: "41" },
  { n: "Suriname", c: "sr", d: "597" },
  { n: "Tadjiquistão", c: "tj", d: "992" },
  { n: "Tailândia", c: "th", d: "66" },
  { n: "Taiwan", c: "tw", d: "886" },
  { n: "Tanzânia", c: "tz", d: "255" },
  { n: "Timor-Leste", c: "tl", d: "670" },
  { n: "Togo", c: "tg", d: "228" },
  { n: "Tonga", c: "to", d: "676" },
  { n: "Trinidad e Tobago", c: "tt", d: "1868" },
  { n: "Tunísia", c: "tn", d: "216" },
  { n: "Turcomenistão", c: "tm", d: "993" },
  { n: "Turquia", c: "tr", d: "90" },
  { n: "Tuvalu", c: "tv", d: "688" },
  { n: "Ucrânia", c: "ua", d: "380" },
  { n: "Uganda", c: "ug", d: "256" },
  { n: "Uruguai", c: "uy", d: "598" },
  { n: "Uzbequistão", c: "uz", d: "998" },
  { n: "Vanuatu", c: "vu", d: "678" },
  { n: "Vaticano", c: "va", d: "379" },
  { n: "Venezuela", c: "ve", d: "58" },
  { n: "Vietnã", c: "vn", d: "84" },
  { n: "Zâmbia", c: "zm", d: "260" },
  { n: "Zimbábue", c: "zw", d: "263" }
];
